spring:
  profiles:
    active: pro
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/deri?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://39.97.96.82:3306/fresh?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #url: jdbc:mysql://120.77.176.74:3306/deri?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #password: b?j.Finanstar...
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
  redis:
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    database: 0
    host: 39.108.48.29
    port: 6379
    password: hiram
    timeout: 0
  http:
    encoding:
      charset: utf8
  mail:
    username: finanstar_robot@qq.com
    password: wjbhggfyzzmcdbdc
    host: smtp.qq.com
#logging:#替换为logback.xml
#file: market.log
