INSERT  INTO
	f_d_order
      ( 
      ID                            
      ,backType                       
      ,deliveryTerminal               
      ,destination                    
      ,goBad                          
      ,itemId                         
      ,orderDate                      
      ,orderStatus                    
      ,orderType                      
      ,transTemperature               
      ,transType                      
      ) 
values
      (
      :fDOrder.id                            
      ,:fDOrder.backtype                      
      ,:fDOrder.deliveryterminal              
      ,:fDOrder.destination                   
      ,:fDOrder.gobad                         
      ,:fDOrder.itemid                        
      ,:fDOrder.orderdate                     
      ,:fDOrder.orderstatus                   
      ,:fDOrder.ordertype                     
      ,:fDOrder.transtemperature              
      ,:fDOrder.transtype                     
      )