INSERT  INTO
	jp_system_auth
      ( 
      id                            
      ,auth_name                      
      ,auth_type                      
      ,auth_desc                      
      ,auth_url                       
      ,parent_id                      
      ,deep                           
      ,sort_no                        
      ,del_flag                       
      ,icon_type                      
      ,create_by                      
      ,create_date                    
      ,update_by                      
      ,update_date                    
      ) 
values
      (
      :jpSystemAuth.id                            
      ,:jpSystemAuth.authName                      
      ,:jpSystemAuth.authType                      
      ,:jpSystemAuth.authDesc                      
      ,:jpSystemAuth.authUrl                       
      ,:jpSystemAuth.parentId                      
      ,:jpSystemAuth.deep                          
      ,:jpSystemAuth.sortNo                        
      ,:jpSystemAuth.delFlag                       
      ,:jpSystemAuth.iconType                      
      ,:jpSystemAuth.createBy                      
      ,:jpSystemAuth.createDate                    
      ,:jpSystemAuth.updateBy                      
      ,:jpSystemAuth.updateDate                    
      )