INSERT  INTO
	jp_system_user
      ( 
      id                            
      ,user_code                      
      ,user_name                      
      ,password                       
      ,user_type                      
      ,user_status                    
      ,last_logn_time                 
      ,last_logn_ip                   
      ,del_flag                       
      ,create_by                      
      ,create_date                    
      ,update_by                      
      ,update_date                    
      ) 
values
      (
      :jpSystemUser.id                            
      ,:jpSystemUser.userCode                      
      ,:jpSystemUser.userName                      
      ,:jpSystemUser.password                      
      ,:jpSystemUser.userType                      
      ,:jpSystemUser.userStatus                    
      ,:jpSystemUser.lastLognTime                  
      ,:jpSystemUser.lastLognIp                    
      ,:jpSystemUser.delFlag                       
      ,:jpSystemUser.createBy                      
      ,:jpSystemUser.createDate                    
      ,:jpSystemUser.updateBy                      
      ,:jpSystemUser.updateDate                    
      )